### ISSUE TITLE
Running ng build as a watcher

### ISSUE THREAD

**Issue by LrsNate** [jdell64/electronAngularBoilerplate#1]
You can run `ng build --watch` to watch for changes and build automatically :)

**Comment by jdell64** [comment]
Good point. Is this a documentation change request?

**Comment by LrsNate** [comment]
More of a suggestion. I can make a pull request if you want me to!

**Comment by jdell64** [comment]
It's a good suggestion! feel free to make a pull request if you like.

## 

Richard J Tindell

Ps 102:18- "This will be written for the generation to come, That a people
yet to be created may praise the Lord."

On Tue, Jul 26, 2016 at 6:00 PM, Antoine Lafouasse <notifications@github.com
